<?php

namespace Database\Seeders;

use App\Models\Academia;
use App\Models\Comentario;
use App\Models\CQueja;
use App\Models\Materia;
use App\Models\Profesor;
use App\Models\ProfesorMateria;
use App\Models\Queja;
use App\Models\ReporteCom;
use App\Models\ReporteQuj;
use App\Models\ReportesQuj;
use App\Models\User;
use App\Models\Users;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {   
        Role::create(['name' => 'usuario']);
        Role::create(['name' => 'moderador']);
        Role::create(['name' => 'administrador']);

        $admin = User::create([
            'name' => 'Angel',
            'first_last_name' => 'Baez',
            'second_last_name' => 'Simon',
            'email' => 'admin@correo.com',
            'email_verified_at' => now(),
            'password' => Hash::make('password'),
            'is_auth' => 1
        ]);
        $admin->assignRole('administrador');

        $moderador = User::create([
            'name' => 'Angel',
            'first_last_name' => 'Baez',
            'second_last_name' => 'Simon',
            'email' => 'moderador@correo.com',
            'email_verified_at' => now(),
            'password' => Hash::make('password'),
            'is_auth' => 1
        ]);
        $moderador->assignRole('moderador');

        $materias = [
            ['nombre' => 'DIBUJO ASISTIDO POR COMPUTADORA'],
            ['nombre' => 'METODOLOGIA DE LA INGENIERIA'],
            ['nombre' => 'PROYECTO DE VIAS TERRESTRES'],
            ['nombre' => 'DIBUJO INDUSTRIAL ASISTIDO POR COMPUTADORA'],
            ['nombre' => 'DINAMICA DE MECANISMOS'],
            ['nombre' => 'MECANICA DE MATERIALES'],
            ['nombre' => 'ELECTRICIDAD Y ELECTRONICA'],
            ['nombre' => 'INSTRUMENTACION Y CONTROL INDUSTRIAL'],
            ['nombre' => 'GESTION DEL MANTENIMIENTO'],
            ['nombre' => 'INSTRUMENTACION Y CONTROL'],
            ['nombre' => 'MANTENIMIENTO'],
            ['nombre' => 'FUNDAMENTOS DE INGENIERIA CIVIL Y ARQUITECTURA'],
            ['nombre' => 'SUMINISTRO DE COMBUSTIBLE Y ENERGIA ELECTRICA'],
            ['nombre' => 'VIAS Y DISEÑO GEOMETRICO DEL TRAZO'],
            ['nombre' => 'INGENIERIA BASICA Y PROYECTOS EJECUTIVOS'],
            ['nombre' => 'CONTRATACION Y EJECUCION DE OBRAS FERROVIARIAS'],
            ['nombre' => 'MANTENIMIENTO DE OBRAS E INSTALACIONES FIJAS'],
            ['nombre' => 'SISTEMAS OPERATIVOS'],
            ['nombre' => 'ARQUITECTURA Y ORGANIZACION DE LAS COMPUTADORAS'],
            ['nombre' => 'COMUNICACION DE DATOS'],
            ['nombre' => 'PROGRAMACION DE BAJO NIVEL'],
            ['nombre' => 'VIROLOGIA Y CRIPTOGRAFIA'],
            ['nombre' => 'COMPUTACION UBICUA'],
            ['nombre' => 'APLICACIONES MULTIMEDIA'],
            ['nombre' => '.NET'],
            ['nombre' => 'APLICACIONES MULTIMEDIA (OPTATIVA III)'],
            ['nombre' => 'LOGICA DE PROGRAMACION'],
            ['nombre' => 'PROGRAMACION WEB'],
            ['nombre' => 'PROGRAMACION ORIENTADA A OBJETOS'],
            ['nombre' => 'INTERNET DE LAS COSAS'],
            ['nombre' => 'SISTEMAS DIGITALES'],
            ['nombre' => 'PROYECTO DE TITULACION'],
            ['nombre' => 'AUTOMATIZACION CON MICROCONTROLADORES'],
            ['nombre' => 'PROGRAMACION MOVIL'],
            ['nombre' => 'ALGORITMOS COMPUTACIONALES'],
            ['nombre' => 'JAVA'],
            ['nombre' => 'DISEÑO DE AMBIENTES UBICUOS'],
            ['nombre' => 'SEGURIDAD EN REDES'],
            ['nombre' => 'REDES Y CONECTIVIDAD'],
            ['nombre' => 'REDES'],
            ['nombre' => 'REALIDAD AUMENTADA'],
            ['nombre' => 'TEORIA DE LA COMPUTACION Y COMPILADORES'],
            ['nombre' => 'SEGURIDAD DE REDES'],
            ['nombre' => 'PROGRAMACION DE DISPOSITIVOS MOVILES'],
            ['nombre' => 'VIROLOGIA Y CRIPTOGRAFIA (OPTATIVA II)'],
            ['nombre' => 'ADQUISICION DE DATOS'],
            ['nombre' => 'COMPUTO EN LA NUBE'],
            ['nombre' => 'APLICACIONES DE REDES'],
            ['nombre' => 'APLICACION DE SISTEMAS DIGITALES'],
            ['nombre' => 'SIMULADORES VIRTUALES (OPTATIVA III)'],
            ['nombre' => 'MONITOREO Y ADMINISTRACION DE REDES (OPTATIVA III)'],
            ['nombre' => 'HERRAMIENTAS MULTIMEDIA'],
            ['nombre' => 'TEORIA DE COMPUTACION Y COMPILADORES'],
            ['nombre' => 'DISEÑO DE INTERFACES DE USUARIO'],
            ['nombre' => 'ESCENARIOS VIRTUALES (OPTATIVA I)'],
            ['nombre' => 'MODELADO GRAFICO DE INTERFASES (OPTATIVA II)'],
            ['nombre' => 'AMBIENTES VIRTUALES INMERSIVOS (OPTATIVA II)'],
            ['nombre' => 'FUNDAMENTOS DE ADMINISTRACION'],
            ['nombre' => 'PLAN DE VIDA'],
            ['nombre' => 'SISTEMAS Y ESTRUCTURAS ORGANIZACIONALES'],
            ['nombre' => 'ADMINISTRACION INTEGRAL'],
            ['nombre' => 'PLANEACIÒN ESTRATÈGICA'],
            ['nombre' => 'PLANEACION ESTRATEGICA'],
            ['nombre' => 'COMPORTAMIENTO ORGANIZACIONAL'],
            ['nombre' => 'GENERACION E INNOV. DE NEG.'],
            ['nombre' => 'MODELOS DE DESARROLLO SUSTENTABLE'],
            ['nombre' => 'GESTION Y MEJORA DE LA PROD. Y CAL.'],
            ['nombre' => 'DESARROLLO EMPRENDEDOR'],
            ['nombre' => 'LIDERAZGO Y DESARROLLO DIRECTIVO'],
            ['nombre' => 'DIRECCION ESTRATEGICA'],
            ['nombre' => 'CONTROL ADMINISTRATIVO'],
            ['nombre' => 'DISEÑO Y DOCUMENTACION DE SISTEMAS DE GESTION'],
            ['nombre' => 'CONSULTORIA'],
            ['nombre' => 'GESTION DE CAMBIO ORGANIZACIONAL'],
            ['nombre' => 'HABILIDADES DIRECTIVAS'],
            ['nombre' => 'AUDITORIA PARA SISTEMAS DE GESTION INTEGRAL'],
            ['nombre' => 'GENERACION E INNOVACION DE NEGOCIOS'],
            ['nombre' => 'SISTEMAS DE GESTION'],
            ['nombre' => 'LIDERAZGO EMPRESARIAL Y RESPONSABILIDAD SOCIAL (OPTATIVA)'],
            ['nombre' => 'MECANICA CLASICA'],
            ['nombre' => 'MECANICA CLASICA APLICADA'],
            ['nombre' => 'FUNDAMENTOS DE FISICA'],
            ['nombre' => 'CALCULO VECTORIAL'],
            ['nombre' => 'ELEMENTOS DEL CALCULO VECTORIAL'],
            ['nombre' => 'ELECTROMAGNETISMO APLICADO'],
            ['nombre' => 'DINAMICA TREN -VIA'],
            ['nombre' => 'ELECTROMAGNETISMO'],
            ['nombre' => 'PSICOLOGIA EN EL TRABAJO'],
            ['nombre' => 'COMUNICACION PROF. INTERDISC.'],
            ['nombre' => 'PSICOLOGIA DEL TRABAJO'],
            ['nombre' => 'HUM IV: DESARROLLO PERSONAL Y PROF.'],
            ['nombre' => 'PSICOSOCIOLOGIA INDUSTRIAL'],
            ['nombre' => 'METODOLOGIA DE LA INVESTIGACION'],
            ['nombre' => 'RESPONSABILIDAD SOCIAL Y ETICA'],
            ['nombre' => 'HABILIDADES DEL PENSAMIENTO'],
            ['nombre' => 'LAB. DE ELECTROMAGNETISMO'],
            ['nombre' => 'LAB. DE MECANICA CLASICA'],
            ['nombre' => 'FISICA GENERAL EXPERIMENTAL'],
            ['nombre' => 'QUIMICA ENERGETICA Y AMBIENTAL'],
            ['nombre' => 'LAB DE QUIMICA INDUSTRIAL'],
            ['nombre' => 'LAB DE QUIMICA APLICADA'],
            ['nombre' => 'LAB. DE QUIMICA ENERGETICA Y AMB.'],
            ['nombre' => 'LAB. PROCESOS INDUSTRIALES'],
            ['nombre' => 'LAB. DE APLICACION DE PROCESOS IND'],
            ['nombre' => 'PROBABILIDAD'],
            ['nombre' => 'ESTADISTICA'],
            ['nombre' => 'FUNDAMENTOS MATEMATICOS'],
            ['nombre' => 'INTEGRACION Y MAT. FINANCIERAS'],
            ['nombre' => 'CALCULO DIF. E INT.'],
            ['nombre' => 'METODOS MATEMATICOS DE LA ING.'],
            ['nombre' => 'MATEMATICAS DISCRETAS'],
            ['nombre' => 'CALCULO INTEGRAL'],
            ['nombre' => 'ALGEBRA LINEAL'],
            ['nombre' => 'METODOS NUMERICOS'],
            ['nombre' => 'CALCULO DIFERENCIAL'],
            ['nombre' => 'METODOS MATEMATICOS'],
            ['nombre' => 'MATEMATICAS APLICADAS'],
            ['nombre' => 'PROBABILIDAD Y ESTADISTICA'],

        ];

        $academias = [
            ['nombre' => 'CIENCIAS BASICAS DE LA INGENIERIA'],
            ['nombre' => 'COMPUTACION'],
            ['nombre' => 'ADMINISTRACION'],
            ['nombre' => 'FISICA'],
            ['nombre' => 'HUMANIDADES Y C. S.'],
            ['nombre' => 'LAB. DE FISICA'],
            ['nombre' => 'LAB. QUIMICA'],
            ['nombre' => 'MATEMATICAS'],
        ];

        $c_quejas = [
          ['nombre' => 'Relaciones inapropiadas con Alumnos'],
          ['nombre' => 'Relaciones inapropiadas con Profesores'],
          ['nombre' => 'Sin plan claro de estudios'],
          ['nombre' => 'Informacion confusa/contradictoria'],
          ['nombre' => 'Trato grosero/sarcastico'],
          ['nombre' => 'Criterios de Evaluacion confusos'],
          ['nombre' => 'Cancelacion de clases sin previo aviso'],
          ['nombre' => 'Discriminacion o Favoritismo'], 
          ['nombre' => 'Ignorancia de alumnos'],
          ['nombre' => 'Sin libertad de opinion'],
          ['nombre' => 'Ridiculizacion de alumnos'],
          ['nombre' => 'Irrespetuoso con la diversidad']
        ];

        $profesores = [
        ['nombre_completo' => 'CARMONA CRISTOBAL RAFAEL ABRAHAM', 'academias_id' => '1', 'fecha_nacimiento' => '1998-03-12'],
        ['nombre_completo' => 'CAMBRON VILLANUEVA PAOLA', 'academias_id' => '1', 'fecha_nacimiento' => '1985-07-25'],
        ['nombre_completo' => 'GRAJEDA CABRERA ALEJANDRO', 'academias_id' => '1', 'fecha_nacimiento' => '1990-11-03'],
        ['nombre_completo' => 'SANCHEZ CABRERA OSWALDO ISRAEL', 'academias_id' => '1', 'fecha_nacimiento' => '2000-06-17'],
        ['nombre_completo' => 'MENDEZ PALAFOX FERNANDO', 'academias_id' => '1', 'fecha_nacimiento' => '1983-02-09'],
        ['nombre_completo' => 'CRUZ SANCHEZ PABLO', 'academias_id' => '1', 'fecha_nacimiento' => '1995-09-29'],
        ['nombre_completo' => 'GARCIA MENDEZ VERONICA', 'academias_id' => '1', 'fecha_nacimiento' => '1976-05-14'],
        ['nombre_completo' => 'PRADO PONCE SERAFIN', 'academias_id' => '1', 'fecha_nacimiento' => '2003-01-06'],
        ['nombre_completo' => 'RAMOS MARTINEZ NORMA CRISTINA', 'academias_id' => '1', 'fecha_nacimiento' => '1999-08-20'],
        ['nombre_completo' => 'AMADOR TORRES VICTOR MARIO', 'academias_id' => '1', 'fecha_nacimiento' => '1988-04-01'],
        ['nombre_completo' => 'PEREZ VILLEDA JOSE ALFREDO', 'academias_id' => '1', 'fecha_nacimiento' => '1993-12-11'],
        ['nombre_completo' => 'MARTEL GUZMAN VICENTE', 'academias_id' => '1', 'fecha_nacimiento' => '1965-06-30'],
        ['nombre_completo' => 'ROSAS PALACIOS JUAN CARLOS', 'academias_id' => '1', 'fecha_nacimiento' => '2001-07-19'],
        ['nombre_completo' => 'JIMENEZ ALVAREZ LAURO ALFONSO', 'academias_id' => '1', 'fecha_nacimiento' => '1980-10-05'],
        ['nombre_completo' => 'ROSALES DE LA VEGA SERGIO ALONSO', 'academias_id' => '1', 'fecha_nacimiento' => '1992-11-22'],
        ['nombre_completo' => 'MAYEN MORELOS ALFONSO', 'academias_id' => '1', 'fecha_nacimiento' => '1978-08-27'],
        ['nombre_completo' => 'DOMINGUEZ BARONA HECTOR', 'academias_id' => '1', 'fecha_nacimiento' => '1987-03-04'],
        ['nombre_completo' => 'HERNANDEZ MEJIA OSVALDO DANIEL', 'academias_id' => '1', 'fecha_nacimiento' => '2005-10-28'],
        ['nombre_completo' => 'MEDINA MARQUEZ ISMAEL', 'academias_id' => '1', 'fecha_nacimiento' => '1984-05-07'],
        ['nombre_completo' => 'RAMIREZ SANDOVAL ALEJANDRA', 'academias_id' => '1', 'fecha_nacimiento' => '2002-06-16'],
        ['nombre_completo' => 'GOMEZ ARAGON LAURA ANGELICA', 'academias_id' => '2', 'fecha_nacimiento' => '1997-01-24'],
        ['nombre_completo' => 'CASILLAS RIVAS ALEJANDRO', 'academias_id' => '2', 'fecha_nacimiento' => '1989-03-10'],
        ['nombre_completo' => 'SANCHEZ SOLORZANO EDUARDO', 'academias_id' => '2', 'fecha_nacimiento' => '2004-07-08'],
        ['nombre_completo' => 'GONZALEZ JIMENEZ MIGUEL ANGEL', 'academias_id' => '2', 'fecha_nacimiento' => '1973-02-21'],
        ['nombre_completo' => 'CARDENAS JUAREZ YULLENI', 'academias_id' => '2', 'fecha_nacimiento' => '1994-06-15'],
        ['nombre_completo' => 'INIESTRA NAVARRETE GABRIEL', 'academias_id' => '2', 'fecha_nacimiento' => '1986-09-03'],
        ['nombre_completo' => 'ORTEGA PACHECO JOSE DAVID', 'academias_id' => '2', 'fecha_nacimiento' => '1991-04-26'],
        ['nombre_completo' => 'RICO ARAGON DANIEL OSWALDO', 'academias_id' => '2', 'fecha_nacimiento' => '1998-10-18'],
        ['nombre_completo' => 'VELASCO CONTRERAS JOSE ANTONIO', 'academias_id' => '2', 'fecha_nacimiento' => '1982-12-31'],
        ['nombre_completo' => 'BUENO VASQUEZ FRANCISCO JAVIER', 'academias_id' => '2', 'fecha_nacimiento' => '1995-06-02'],
        ['nombre_completo' => 'RODRIGUEZ CALDERON DE LA BARCA CARLOS RODRIGO', 'academias_id' => '2', 'fecha_nacimiento' => '1979-08-09'],
        ['nombre_completo' => 'DIAZ VILLA CAMILA', 'academias_id' => '2', 'fecha_nacimiento' => '1993-05-17'],
        ['nombre_completo' => 'MARTINEZ TLAHUEL MIGUEL ANGEL', 'academias_id' => '2', 'fecha_nacimiento' => '1988-09-06'],
        ['nombre_completo' => 'VIERA HARO JORGE', 'academias_id' => '2', 'fecha_nacimiento' => '1990-03-20'],
        ['nombre_completo' => 'CASTRO MENDEZ GILBERTO SAUL', 'academias_id' => '2', 'fecha_nacimiento' => '2006-10-11'],
        ['nombre_completo' => 'LECHUGA BLANCO FATIMA', 'academias_id' => '2', 'fecha_nacimiento' => '1968-01-14'],
        ['nombre_completo' => 'REYES ENCISO JUAN ROBERTO', 'academias_id' => '2', 'fecha_nacimiento' => '1981-07-23'],
        ['nombre_completo' => 'CUEVAS ESCOBAR SUSANA', 'academias_id' => '2', 'fecha_nacimiento' => '1999-12-07'],
        ['nombre_completo' => 'GARDUÑO MENDIETA VICTOR', 'academias_id' => '2', 'fecha_nacimiento' => '1996-01-29'],
        ['nombre_completo' => 'MIRANDA CHAVEZ EDNA MARTHA', 'academias_id' => '2', 'fecha_nacimiento' => '2000-11-05'],
        ['nombre_completo' => 'SEGUNDO MIRANDA JUAN ALBERTO', 'academias_id' => '2', 'fecha_nacimiento' => '1974-08-30'],
        ['nombre_completo' => 'JESUS CARRILLO CARLOS', 'academias_id' => '2', 'fecha_nacimiento' => '2003-04-19'],
        ['nombre_completo' => 'AVALOS LUNA ALFONSO', 'academias_id' => '2', 'fecha_nacimiento' => '1982-06-12'],
        ['nombre_completo' => 'LOPEZ GOYTIA JOSE LUIS', 'academias_id' => '2', 'fecha_nacimiento' => '2004-02-27'],
        ['nombre_completo' => 'RIVERA PEREZ ALFREDO', 'academias_id' => '2', 'fecha_nacimiento' => '1998-10-01'],
        ['nombre_completo' => 'MACHORRO REYES RICARDO ARMANDO', 'academias_id' => '2', 'fecha_nacimiento' => '1985-08-16'],
        ['nombre_completo' => 'HERNANDEZ CERON RICARDO', 'academias_id' => '2', 'fecha_nacimiento' => '1972-11-08'],
        ['nombre_completo' => 'RODRIGUEZ JOSE LUIS', 'academias_id' => '2', 'fecha_nacimiento' => '2002-01-03'],
        ['nombre_completo' => 'ORTIZ CASTREJON NANCY LORENA', 'academias_id' => '2', 'fecha_nacimiento' => '1997-05-22'],
        ['nombre_completo' => 'LOPEZ HARO JOSE DE JESUS', 'academias_id' => '2', 'fecha_nacimiento' => '1986-04-14'],
        ['nombre_completo' => 'GUZMAN CORDERO MARIA CRISTINA', 'academias_id' => '2', 'fecha_nacimiento' => '1991-12-06'],
        ['nombre_completo' => 'LECHUGA BLANCO FATIMA MARGARITA', 'academias_id' => '2', 'fecha_nacimiento' => '2000-02-25'],
        ['nombre_completo' => 'MENESES GONZALEZ RAYMUNDO', 'academias_id' => '2', 'fecha_nacimiento' => '1980-06-18'],
        ['nombre_completo' => 'BUSTAMANTE TRANQUILINO ROCIO', 'academias_id' => '2', 'fecha_nacimiento' => '1994-05-30'],
        ['nombre_completo' => 'MARTINEZ VAZQUEZ GUSTAVO', 'academias_id' => '2', 'fecha_nacimiento' => '1999-08-10'],
        ['nombre_completo' => 'MELENDEZ MANRIQUE ABEL', 'academias_id' => '2', 'fecha_nacimiento' => '1987-07-04'],
        ['nombre_completo' => 'LUQUE MARQUEZ FERNANDO', 'academias_id' => '2', 'fecha_nacimiento' => '2005-03-21'],
        ['nombre_completo' => 'SONCK LEDESMA JUDITH', 'academias_id' => '2', 'fecha_nacimiento' => '1983-01-12'],
        ['nombre_completo' => 'ANGELES JACINTO ARTURO', 'academias_id' => '2', 'fecha_nacimiento' => '1975-09-28'],
        ['nombre_completo' => 'HUERTA VALDEPEÑA ERICK', 'academias_id' => '2', 'fecha_nacimiento' => '2001-06-09'],
        ['nombre_completo' => 'LOPEZ VALERIANO ILIANA YAZMIN', 'academias_id' => '2', 'fecha_nacimiento' => '1989-02-02'],
        ['nombre_completo' => 'GONZALEZ DE LA O FRANCISCO FABIAN', 'academias_id' => '2', 'fecha_nacimiento' => '1990-07-16'],
        ['nombre_completo' => 'MENDEZ GIRON ALEJANDRA MARGARITA', 'academias_id' => '2', 'fecha_nacimiento' => '1981-04-07'],
        ['nombre_completo' => 'MENDEZ GARCIA SARA', 'academias_id' => '2', 'fecha_nacimiento' => '2006-10-23'],
        ['nombre_completo' => 'CHAVEZ PEREZ JOSE LUIS', 'academias_id' => '2', 'fecha_nacimiento' => '1995-05-19'],
        ['nombre_completo' => 'JUAREZ TREVIÑO JUAN MANUEL', 'academias_id' => '2', 'fecha_nacimiento' => '1970-01-31'],
        ['nombre_completo' => 'MORTERA ZENTENO CARLOS', 'academias_id' => '2', 'fecha_nacimiento' => '2004-08-13'],
        ['nombre_completo' => 'GALLARDO SANCHEZ VICTOR ALFREDO', 'academias_id' => '2', 'fecha_nacimiento' => '1996-12-03'],
        ['nombre_completo' => 'FUENLABRADA VELAZQUEZ SERGIO', 'academias_id' => '2', 'fecha_nacimiento' => '1978-06-26'],
        ['nombre_completo' => 'CANELA LUNA ALFREDO', 'academias_id' => '2', 'fecha_nacimiento' => '1982-03-01'],
        ['nombre_completo' => 'SESMA MARTINEZ MARIO ALBERTO', 'academias_id' => '2', 'fecha_nacimiento' => '1998-07-22'],
        ['nombre_completo' => 'HERNANDEZ RAMIREZ VICTOR HUGO', 'academias_id' => '2', 'fecha_nacimiento' => '2002-11-11'],
        ['nombre_completo' => 'MONTES CASIANO HERMES FRANCISCO', 'academias_id' => '2', 'fecha_nacimiento' => '1980-03-08'],
        ['nombre_completo' => 'AZORIN VEGA CLAUDIA GUILLERMINA', 'academias_id' => '2', 'fecha_nacimiento' => '1991-10-17'],
        ['nombre_completo' => 'MOLINA BAÑUELOS BELINDA', 'academias_id' => '3', 'fecha_nacimiento' => '1984-12-15'],
        ['nombre_completo' => 'GONZALEZ MILLAN GEORGINA', 'academias_id' => '3', 'fecha_nacimiento' => '1993-06-06'],
        ['nombre_completo' => 'HERNANDEZ VICTOR MIGUEL', 'academias_id' => '3', 'fecha_nacimiento' => '1997-09-25'],
        ['nombre_completo' => 'TORREBLANCA DOMINGUEZ OFELIA', 'academias_id' => '3', 'fecha_nacimiento' => '1976-02-20'],
        ['nombre_completo' => 'MARTINEZ TRUJILLO JAQUELINE', 'academias_id' => '3', 'fecha_nacimiento' => '2000-11-29'],
        ['nombre_completo' => 'LOPEZ BEJARANO GRACIELA', 'academias_id' => '3', 'fecha_nacimiento' => '2003-01-05'],
        ['nombre_completo' => 'GARCIA MARTINEZ JOSE GUADALUPE', 'academias_id' => '3', 'fecha_nacimiento' => '1985-10-12'],
        ['nombre_completo' => 'MENDOZA NAVARRO MONICA', 'academias_id' => '3', 'fecha_nacimiento' => '1992-06-04'],
        ['nombre_completo' => 'ALCANTARA GONZALEZ ANITA', 'academias_id' => '3', 'fecha_nacimiento' => '1969-09-18'],
        ['nombre_completo' => 'ARELLANO ALAVEZ CUAUHTEMOC', 'academias_id' => '3', 'fecha_nacimiento' => '1999-03-27'],
        ['nombre_completo' => 'MONDRAGON VALDEZ ELVIA', 'academias_id' => '3', 'fecha_nacimiento' => '2001-07-30'],
        ['nombre_completo' => 'GODINEZ TORRES MARLIN SANDRA', 'academias_id' => '3', 'fecha_nacimiento' => '1988-01-09'],
        ['nombre_completo' => 'CASTRO SEGURA MARÌA DEL PILAR', 'academias_id' => '3', 'fecha_nacimiento' => '1974-05-14'],
        ['nombre_completo' => 'HERNANDEZ ORTIZ MARBELL', 'academias_id' => '3', 'fecha_nacimiento' => '1983-11-21'],
        ['nombre_completo' => 'DEL VALLE GARCIA DIANA', 'academias_id' => '3', 'fecha_nacimiento' => '2006-02-16'],
        ['nombre_completo' => 'RODRIGUEZ ALARCON HUGO DAVID', 'academias_id' => '3', 'fecha_nacimiento' => '1982-08-02'],
        ['nombre_completo' => 'FONSECA MONTERRUBIO LAURA ANDROMEDA', 'academias_id' => '3', 'fecha_nacimiento' => '1990-04-10'],
        ['nombre_completo' => 'SILVA MENDOZA EDITH ROSA', 'academias_id' => '3', 'fecha_nacimiento' => '1986-01-06'],
        ['nombre_completo' => 'ARMAS GUZMAN SILVIA MARCELA', 'academias_id' => '3', 'fecha_nacimiento' => '2000-08-19'],
        ['nombre_completo' => 'JUAREZ VASQUEZ ALBERTO', 'academias_id' => '3', 'fecha_nacimiento' => '1996-12-01'],
        ['nombre_completo' => 'FLORES SÀNCHEZ MARIA DELR ROCÌO', 'academias_id' => '3', 'fecha_nacimiento' => '1987-03-13'],
        ['nombre_completo' => 'FORTIS VAZQUEZ ALMA ALICIA', 'academias_id' => '3', 'fecha_nacimiento' => '2004-10-24'],
        ['nombre_completo' => 'MENDOZA NARVAEZ ANTONIO', 'academias_id' => '3', 'fecha_nacimiento' => '1994-07-07'],
        ['nombre_completo' => 'CORTÈS NAVARRO JOSÈ MIGUEL', 'academias_id' => '3', 'fecha_nacimiento' => '1981-12-28'],
        ['nombre_completo' => 'DIAZ SANCHEZ ANTONIO', 'academias_id' => '3', 'fecha_nacimiento' => '1990-09-20'],
        ['nombre_completo' => 'BLASQUEZ PICO RUSALIA', 'academias_id' => '3', 'fecha_nacimiento' => '1998-01-15'],
        ['nombre_completo' => 'MAGDALENO MARTINEZ VICTOR', 'academias_id' => '3', 'fecha_nacimiento' => '1983-06-03'],
        ['nombre_completo' => 'MEDINA REYES SERGIO', 'academias_id' => '3', 'fecha_nacimiento' => '2002-05-11'],
        ['nombre_completo' => 'YAÑEZ NIETO RICARDO', 'academias_id' => '3', 'fecha_nacimiento' => '1977-11-26'],
        ['nombre_completo' => 'MEJIA CHAVEZ NICOLAS', 'academias_id' => '3', 'fecha_nacimiento' => '1991-02-06'],
        ['nombre_completo' => 'VARGAS MONTIEL NANCY JUDITH', 'academias_id' => '3', 'fecha_nacimiento' => '2005-08-23'],
        ['nombre_completo' => 'LEYVA CASTILLO MARTA', 'academias_id' => '3', 'fecha_nacimiento' => '1988-04-17'],
        ['nombre_completo' => 'MENDEZ BORJA ANGELICA', 'academias_id' => '3', 'fecha_nacimiento' => '1994-10-09'],
        ['nombre_completo' => 'MEDELLÌN RUIZ LAURA', 'academias_id' => '3', 'fecha_nacimiento' => '1979-07-01'],
        ['nombre_completo' => 'CRUZ RODRIGUEZ DAVID SALVADOR', 'academias_id' => '3', 'fecha_nacimiento' => '2001-12-13'],
        ['nombre_completo' => 'GONZALEZ DE LA RIVA JOSEFINA', 'academias_id' => '3', 'fecha_nacimiento' => '2006-03-25'],
        ['nombre_completo' => 'NORIEGA MEZA MARCO ANTONIO', 'academias_id' => '3', 'fecha_nacimiento' => '1985-09-04'],
        ['nombre_completo' => 'COSSIO CRUZ DINA ARELI', 'academias_id' => '3', 'fecha_nacimiento' => '1996-10-30'],
        ['nombre_completo' => 'GARCIA PEDRAZA ROCÌO', 'academias_id' => '3', 'fecha_nacimiento' => '1980-08-10'],
        ['nombre_completo' => 'GARCÌA ROMERO HECTOR ALBERTO', 'academias_id' => '3', 'fecha_nacimiento' => '1999-04-08'],
        ['nombre_completo' => 'CABALLERO ROSALES JAQUELINE', 'academias_id' => '3', 'fecha_nacimiento' => '1992-12-18'],
        ['nombre_completo' => 'GONZALEZ ROGEL MARICRUZ', 'academias_id' => '3', 'fecha_nacimiento' => '2003-11-06'],
        ['nombre_completo' => 'HERNÀNDEZ VICTOR MIGUEL', 'academias_id' => '3', 'fecha_nacimiento' => '1995-07-27'],
        ['nombre_completo' => 'SERNA SOLÌS NAPOLEÒN', 'academias_id' => '3', 'fecha_nacimiento' => '1987-01-22'],
        ['nombre_completo' => 'MENDOZA VARGAS VIRIDIANA', 'academias_id' => '3', 'fecha_nacimiento' => '2004-05-03'],
        ['nombre_completo' => 'CARMONA CRISTOBAL RAFAEL ABRAHAM', 'academias_id' => '3', 'fecha_nacimiento' => '1998-03-12'],
        ['nombre_completo' => 'RAMÌREZ HERNÀNDEZ RENÈ', 'academias_id' => '3', 'fecha_nacimiento' => '1993-09-14'],
        ['nombre_completo' => 'VÀZQUEZ JUÀREZ ALBERTO', 'academias_id' => '3', 'fecha_nacimiento' => '1964-02-07'],
        ['nombre_completo' => 'RIVERA VALDEZ SALVADOR', 'academias_id' => '3', 'fecha_nacimiento' => '2002-06-19'],
        ['nombre_completo' => 'PATIÑO SOBERANIS JOSE LUIS', 'academias_id' => '3', 'fecha_nacimiento' => '1997-03-28'],
        ['nombre_completo' => 'GARCIA PEDRAZA ROCIO', 'academias_id' => '3', 'fecha_nacimiento' => '1986-12-02'],
        ['nombre_completo' => 'PULIDO MALDONADO ILIANA', 'academias_id' => '3', 'fecha_nacimiento' => '2000-10-16'],
        ['nombre_completo' => 'ARREDONDO CUE JOGE MARTIN', 'academias_id' => '3', 'fecha_nacimiento' => '1991-05-31'],
        ['nombre_completo' => 'TREJO GARCIA MA. ROSARIO', 'academias_id' => '3', 'fecha_nacimiento' => '1976-07-11'],
        ['nombre_completo' => 'ARREDONDO CUE JORGE MARTIN', 'academias_id' => '3', 'fecha_nacimiento' => '1998-08-05'],
        ['nombre_completo' => 'TRUJILLO TRUJILLO OLGA', 'academias_id' => '3', 'fecha_nacimiento' => '1984-06-24'],
        ['nombre_completo' => 'FLORES SÀNCHEZ MARIA DEL ROCÌO', 'academias_id' => '3', 'fecha_nacimiento' => '1989-11-01'],
        ['nombre_completo' => 'ALMEIDA MARTINEZ FLORENTINO', 'academias_id' => '4', 'fecha_nacimiento' => '2005-04-12'],
        ['nombre_completo' => 'AUSTRIA PEREZ JOSUE', 'academias_id' => '4', 'fecha_nacimiento' => '1996-07-20'],
        ['nombre_completo' => 'BADILLO RUIZ CARLOS ALBERTO', 'academias_id' => '4', 'fecha_nacimiento' => '2001-03-06'],
        ['nombre_completo' => 'BELTRAN DE PAZ RUBEN', 'academias_id' => '4', 'fecha_nacimiento' => '1982-09-09'],
        ['nombre_completo' => 'BERNAL MEZA ANDRES UCIEL', 'academias_id' => '4', 'fecha_nacimiento' => '1994-01-26'],
        ['nombre_completo' => 'COTE GUTIERREZ FAUSTO', 'academias_id' => '4', 'fecha_nacimiento' => '1986-08-15'],
        ['nombre_completo' => 'CRUZ RUIZ JULIO DAVID', 'academias_id' => '4', 'fecha_nacimiento' => '1971-04-29'],
        ['nombre_completo' => 'GALLARDO HERNANDEZ VICTOR M.', 'academias_id' => '4', 'fecha_nacimiento' => '1995-02-04'],
        ['nombre_completo' => 'GARCIA MANRIQUE EDGAR', 'academias_id' => '4', 'fecha_nacimiento' => '2000-06-23'],
        ['nombre_completo' => 'GUTIERREZ GARCIA XINAH HERON', 'academias_id' => '4', 'fecha_nacimiento' => '2003-10-13'],
        ['nombre_completo' => 'GUTIERREZ TREJO LUIS RAMON', 'academias_id' => '4', 'fecha_nacimiento' => '1978-11-30'],
        ['nombre_completo' => 'HARO AGUILAR GABRIEL', 'academias_id' => '4', 'fecha_nacimiento' => '1993-01-10'],
        ['nombre_completo' => 'HERNANDEZ AGUILAR ITANDEHUI', 'academias_id' => '4', 'fecha_nacimiento' => '1997-08-22'],
        ['nombre_completo' => 'JIMENEZ LOPEZ ENRIQUE', 'academias_id' => '4', 'fecha_nacimiento' => '2004-07-17'],
        ['nombre_completo' => 'LARA CAMILO ARMANDO', 'academias_id' => '4', 'fecha_nacimiento' => '1990-10-03'],
        ['nombre_completo' => 'LOPEZ GOVEA JOSE LUIS', 'academias_id' => '4', 'fecha_nacimiento' => '1989-06-12'],
        ['nombre_completo' => 'MARTINEZ RAMOS JAIME', 'academias_id' => '4', 'fecha_nacimiento' => '2002-04-25'],
        ['nombre_completo' => 'MERA OLGUIN SILVIA', 'academias_id' => '4', 'fecha_nacimiento' => '1987-03-07'],
        ['nombre_completo' => 'OCHOA CANO JOSE MA. ALFONSO', 'academias_id' => '4', 'fecha_nacimiento' => '1972-08-31'],
        ['nombre_completo' => 'PICHAL CERDA FRANCISCO', 'academias_id' => '4', 'fecha_nacimiento' => '1994-12-19'],
        ['nombre_completo' => 'AYUSO NARANJO MARIA ELOISA', 'academias_id' => '5', 'fecha_nacimiento' => '1996-07-05'],
        ['nombre_completo' => 'CONTRERAS RODRIGUEZ ZITA LILIA', 'academias_id' => '5', 'fecha_nacimiento' => '2000-11-02'],
        ['nombre_completo' => 'CRUZ ESTRADA MARIA CRISTINA', 'academias_id' => '5', 'fecha_nacimiento' => '1990-02-27'],
        ['nombre_completo' => 'CRUZ MARTINEZ RAMON', 'academias_id' => '5', 'fecha_nacimiento' => '1985-06-14'],
        ['nombre_completo' => 'DEL CASTILLO NEWMANN ENRIQUE G.', 'academias_id' => '5', 'fecha_nacimiento' => '1983-03-22'],
        ['nombre_completo' => 'FIGUEROA MERCADO JUANA', 'academias_id' => '5', 'fecha_nacimiento' => '1993-09-08'],
        ['nombre_completo' => 'FLORES ROSETE LUCRECIA GPE', 'academias_id' => '5', 'fecha_nacimiento' => '1977-01-18'],
        ['nombre_completo' => 'FLORES ZARATE ARTURO', 'academias_id' => '5', 'fecha_nacimiento' => '1998-06-10'],
        ['nombre_completo' => 'FRAUSTO RODRIGUEZ GABRIELA', 'academias_id' => '5', 'fecha_nacimiento' => '1986-04-03'],
        ['nombre_completo' => 'GARCIA ESPINOSA RICARDO', 'academias_id' => '5', 'fecha_nacimiento' => '2001-05-15'],
        ['nombre_completo' => 'COTE GUTIERREZ FAUSTO', 'academias_id' => '6', 'fecha_nacimiento' => '1986-08-15'],
        ['nombre_completo' => 'CRUZ RUIZ JULIO DAVID', 'academias_id' => '6', 'fecha_nacimiento' => '1971-04-29'],
        ['nombre_completo' => 'ELECTROMAGNETISMO APLICADO', 'academias_id' => '6', 'fecha_nacimiento' => '1974-07-29'],
        ['nombre_completo' => 'GARCIA MANRIQUE EDGAR', 'academias_id' => '6', 'fecha_nacimiento' => '2000-06-23'],
        ['nombre_completo' => 'GUTIERREZ GARCIA XINAH HERON', 'academias_id' => '6', 'fecha_nacimiento' => '2003-10-13'],
        ['nombre_completo' => 'GUTIERREZ TREJO LUIS RAMON', 'academias_id' => '6', 'fecha_nacimiento' => '1978-11-30'],
        ['nombre_completo' => 'HERNANDEZ AGUILAR ITANDEHUI', 'academias_id' => '6', 'fecha_nacimiento' => '1997-08-22'],
        ['nombre_completo' => 'JAIMES CAMACHO ISRAEL MIGUEL', 'academias_id' => '6', 'fecha_nacimiento' => '1981-12-09'],
        ['nombre_completo' => 'LARA CAMILO ARMANDO', 'academias_id' => '6', 'fecha_nacimiento' => '1990-10-03'],
        ['nombre_completo' => 'MERA OLGUIN SILVIA', 'academias_id' => '6', 'fecha_nacimiento' => '1987-03-07'],
        ['nombre_completo' => 'NERIA SUMANO CESAR ALEJANDRO', 'academias_id' => '6', 'fecha_nacimiento' => '1999-08-21'],
        ['nombre_completo' => 'DIAZ MALDONADO INDIRA ELISA', 'academias_id' => '7', 'fecha_nacimiento' => '1984-02-12'],
        ['nombre_completo' => 'ESCALANTE GARCIA LAURA ELOISA', 'academias_id' => '7', 'fecha_nacimiento' => '1992-10-06'],
        ['nombre_completo' => 'FRANCISCO MARQUEZ MISAELA', 'academias_id' => '7', 'fecha_nacimiento' => '2005-11-24'],
        ['nombre_completo' => 'GARCIA MURRIETA MA. DE JESUS', 'academias_id' => '7', 'fecha_nacimiento' => '1980-06-01'],
        ['nombre_completo' => 'HIDALGO OLGUIN DAVID RICARDO', 'academias_id' => '7', 'fecha_nacimiento' => '1997-04-20'],
        ['nombre_completo' => 'MARTINEZ MUÑOZ MARCO A.', 'academias_id' => '7', 'fecha_nacimiento' => '1991-03-11'],
        ['nombre_completo' => 'MONSALVO VAZQUEZ RAUL', 'academias_id' => '7', 'fecha_nacimiento' => '2003-12-30'],
        ['nombre_completo' => 'MORALES DE LA TORRE CARLOS J.', 'academias_id' => '7', 'fecha_nacimiento' => '1990-09-17'],
        ['nombre_completo' => 'MOTA TAPIA LEON FELIPE', 'academias_id' => '7', 'fecha_nacimiento' => '1985-06-05'],
        ['nombre_completo' => 'NAVARRETE MAGAÑA ALEJANDRA M.', 'academias_id' => '7', 'fecha_nacimiento' => '1979-07-13'],
        ['nombre_completo' => 'PEREZ MONROY LUIS ALBERTO', 'academias_id' => '7', 'fecha_nacimiento' => '1996-02-28'],
        ['nombre_completo' => 'PLANOS LOUREIRO ANTONIO', 'academias_id' => '7', 'fecha_nacimiento' => '1988-05-23'],
        ['nombre_completo' => 'POSADA GOMEZ ALICIA', 'academias_id' => '7', 'fecha_nacimiento' => '2000-01-04'],
        ['nombre_completo' => 'QUIROZ CARDOSO OSCAR', 'academias_id' => '7', 'fecha_nacimiento' => '1975-08-16'],
        ['nombre_completo' => 'AGUILAR PEREZ ENRIQUE', 'academias_id' => '8', 'fecha_nacimiento' => '1995-12-07'],
        ['nombre_completo' => 'ALTUZAR CALZADA BRANDON', 'academias_id' => '8', 'fecha_nacimiento' => '1983-10-26'],
        ['nombre_completo' => 'ALVARADO GALVAN JOSE', 'academias_id' => '8', 'fecha_nacimiento' => '2006-04-19'],
        ['nombre_completo' => 'ANGUIANO SANCHEZ OMAR', 'academias_id' => '8', 'fecha_nacimiento' => '1992-03-31'],
        ['nombre_completo' => 'AQUINO LICONA IVAN', 'academias_id' => '8', 'fecha_nacimiento' => '1994-07-02'],
        ['nombre_completo' => 'BECERRIL VIDAL PATROCINIO', 'academias_id' => '8', 'fecha_nacimiento' => '1987-11-15'],
        ['nombre_completo' => 'BENITEZ LOPEZ RUBEN ISRAEL', 'academias_id' => '8', 'fecha_nacimiento' => '1986-08-09'],
        ['nombre_completo' => 'BETANZOS MENDEZ HUGO', 'academias_id' => '8', 'fecha_nacimiento' => '1970-10-22'],
        ['nombre_completo' => 'BOCARDO RAMIREZ ALMA P.', 'academias_id' => '8', 'fecha_nacimiento' => '1993-05-06'],
        ['nombre_completo' => 'CABAÑAS VILLANUEVA BRENDA A.', 'academias_id' => '8', 'fecha_nacimiento' => '1998-09-13'],
        ['nombre_completo' => 'CALVA CRUZ CARLOS', 'academias_id' => '8', 'fecha_nacimiento' => '2003-06-27'],
        ['nombre_completo' => 'CORDOBA LOBO VICTOR MANUEL R.', 'academias_id' => '8', 'fecha_nacimiento' => '1997-11-17'],
        ['nombre_completo' => 'CRISTOBAL VAZQUEZ DONALDO R.', 'academias_id' => '8', 'fecha_nacimiento' => '1982-01-08'],
        ['nombre_completo' => 'CUELLAR GOMEZ MARIO', 'academias_id' => '8', 'fecha_nacimiento' => '1999-10-25'],
        ['nombre_completo' => 'DE LA PAZ CASASOLA EDITH VIOLETA', 'academias_id' => '8', 'fecha_nacimiento' => '1978-07-12'],
        ['nombre_completo' => 'FLORES OROPEZA JOSE LUIS', 'academias_id' => '8', 'fecha_nacimiento' => '1995-02-03'],
        ['nombre_completo' => 'GALICIA TOLEDO GERARDO', 'academias_id' => '8', 'fecha_nacimiento' => '1992-11-22'],
        ['nombre_completo' => 'GARCIA ALVARADO JUAN JOSE', 'academias_id' => '8', 'fecha_nacimiento' => '1978-08-27'],
        ['nombre_completo' => 'GARCIA SOSA FAUSTINO RICARDO', 'academias_id' => '8', 'fecha_nacimiento' => '1987-03-04'],
        ['nombre_completo' => 'GONZALEZ NAVARRETE CARLOS', 'academias_id' => '8', 'fecha_nacimiento' => '1996-09-13'],
        ['nombre_completo' => 'GORDILLO RIVAS KARLA YOLANDA', 'academias_id' => '8', 'fecha_nacimiento' => '2005-10-28']];

        $profesores_materias = [
            ['profesores_id' => 1 , 'materias_id' => 1],
            ['profesores_id' => 2 , 'materias_id' => 2],
            ['profesores_id' => 3 , 'materias_id' => 1],
            ['profesores_id' => 1 , 'materias_id' => 2],
            ['profesores_id' => 4 , 'materias_id' => 1],
            ['profesores_id' => 4 , 'materias_id' => 2],
            ['profesores_id' => 1 , 'materias_id' => 3],
            ['profesores_id' => 5 , 'materias_id' => 3],
            ['profesores_id' => 3 , 'materias_id' => 3],
            ['profesores_id' => 6 , 'materias_id' => 4],
            ['profesores_id' => 7 , 'materias_id' => 4],
            ['profesores_id' => 8 , 'materias_id' => 4],
            ['profesores_id' => 4 , 'materias_id' => 4],
            ['profesores_id' => 9 , 'materias_id' => 5],
            ['profesores_id' => 10 , 'materias_id' => 5],
            ['profesores_id' => 6 , 'materias_id' => 6],
            ['profesores_id' => 11 , 'materias_id' => 7],
            ['profesores_id' => 8 , 'materias_id' => 6],
            ['profesores_id' => 9 , 'materias_id' => 6],
            ['profesores_id' => 12 , 'materias_id' => 6],
            ['profesores_id' => 13 , 'materias_id' => 7],
            ['profesores_id' => 6 , 'materias_id' => 5],
            ['profesores_id' => 14 , 'materias_id' => 5],
            ['profesores_id' => 15 , 'materias_id' => 7],
            ['profesores_id' => 13 , 'materias_id' => 8],
            ['profesores_id' => 16 , 'materias_id' => 8],
            ['profesores_id' => 17 , 'materias_id' => 9],
            ['profesores_id' => 14 , 'materias_id' => 9],
            ['profesores_id' => 15 , 'materias_id' => 9],
            ['profesores_id' => 12 , 'materias_id' => 7],
            ['profesores_id' => 18 , 'materias_id' => 7],
            ['profesores_id' => 19 , 'materias_id' => 8],
            ['profesores_id' => 17 , 'materias_id' => 8],
            ['profesores_id' => 2 , 'materias_id' => 9],
            ['profesores_id' => 13 , 'materias_id' => 10],
            ['profesores_id' => 16 , 'materias_id' => 10],
            ['profesores_id' => 19 , 'materias_id' => 10],
            ['profesores_id' => 2 , 'materias_id' => 11],
            ['profesores_id' => 7 , 'materias_id' => 12],
            ['profesores_id' => 7 , 'materias_id' => 1],
            ['profesores_id' => 3 , 'materias_id' => 12],
            ['profesores_id' => 10 , 'materias_id' => 13],
            ['profesores_id' => 5 , 'materias_id' => 14],
            ['profesores_id' => 3 , 'materias_id' => 15],
            ['profesores_id' => 20 , 'materias_id' => 14],
            ['profesores_id' => 5 , 'materias_id' => 15],
            ['profesores_id' => 20 , 'materias_id' => 16],
            ['profesores_id' => 21 , 'materias_id' => 17],
            ['profesores_id' => 4 , 'materias_id' => 17],
            ['profesores_id' => 22 , 'materias_id' => 18],
            ['profesores_id' => 23 , 'materias_id' => 19],
            ['profesores_id' => 24 , 'materias_id' => 20],
            ['profesores_id' => 25 , 'materias_id' => 21],
            ['profesores_id' => 26 , 'materias_id' => 22],
            ['profesores_id' => 27 , 'materias_id' => 19],
            ['profesores_id' => 28 , 'materias_id' => 19],
            ['profesores_id' => 29 , 'materias_id' => 23],
            ['profesores_id' => 30 , 'materias_id' => 24],
            ['profesores_id' => 31 , 'materias_id' => 24],
            ['profesores_id' => 32 , 'materias_id' => 25],
            ['profesores_id' => 33 , 'materias_id' => 26],
            ['profesores_id' => 34 , 'materias_id' => 18],
            ['profesores_id' => 35 , 'materias_id' => 27],
            ['profesores_id' => 36 , 'materias_id' => 28],
            ['profesores_id' => 34 , 'materias_id' => 29],
            ['profesores_id' => 27 , 'materias_id' => 30],
            ['profesores_id' => 37 , 'materias_id' => 31],
            ['profesores_id' => 34 , 'materias_id' => 32],
            ['profesores_id' => 34 , 'materias_id' => 33],
            ['profesores_id' => 38 , 'materias_id' => 34],
            ['profesores_id' => 32 , 'materias_id' => 35],
            ['profesores_id' => 32 , 'materias_id' => 36],
            ['profesores_id' => 32 , 'materias_id' => 37],
            ['profesores_id' => 18 , 'materias_id' => 38],
            ['profesores_id' => 39 , 'materias_id' => 39],
            ['profesores_id' => 40 , 'materias_id' => 40],
            ['profesores_id' => 41 , 'materias_id' => 29],
            ['profesores_id' => 18 , 'materias_id' => 41],
            ['profesores_id' => 42 , 'materias_id' => 33],
            ['profesores_id' => 43 , 'materias_id' => 42],
            ['profesores_id' => 44 , 'materias_id' => 19],
            ['profesores_id' => 42 , 'materias_id' => 32],
            ['profesores_id' => 45 , 'materias_id' => 27],
            ['profesores_id' => 46 , 'materias_id' => 43],
            ['profesores_id' => 47 , 'materias_id' => 44],
            ['profesores_id' => 48 , 'materias_id' => 45],
            ['profesores_id' => 39 , 'materias_id' => 20],
            ['profesores_id' => 49 , 'materias_id' => 21],
            ['profesores_id' => 50 , 'materias_id' => 46],
            ['profesores_id' => 42 , 'materias_id' => 27],
            ['profesores_id' => 51 , 'materias_id' => 39],
            ['profesores_id' => 52 , 'materias_id' => 47],
            ['profesores_id' => 27 , 'materias_id' => 48],
            ['profesores_id' => 45 , 'materias_id' => 32],
            ['profesores_id' => 53 , 'materias_id' => 49],
            ['profesores_id' => 31 , 'materias_id' => 37],
            ['profesores_id' => 54 , 'materias_id' => 47],
            ['profesores_id' => 55 , 'materias_id' => 50],
            ['profesores_id' => 34 , 'materias_id' => 37],
            ['profesores_id' => 56 , 'materias_id' => 34],
            ['profesores_id' => 30 , 'materias_id' => 51],
            ['profesores_id' => 41 , 'materias_id' => 35],
            ['profesores_id' => 57 , 'materias_id' => 31],
            ['profesores_id' => 18 , 'materias_id' => 44],
            ['profesores_id' => 57 , 'materias_id' => 21],
            ['profesores_id' => 58 , 'materias_id' => 31],
            ['profesores_id' => 59 , 'materias_id' => 28],
            ['profesores_id' => 60 , 'materias_id' => 31],
            ['profesores_id' => 45 , 'materias_id' => 29],
            ['profesores_id' => 31 , 'materias_id' => 28],
            ['profesores_id' => 42 , 'materias_id' => 30],
            ['profesores_id' => 61 , 'materias_id' => 28],
            ['profesores_id' => 62 , 'materias_id' => 28],
            ['profesores_id' => 24 , 'materias_id' => 47],
            ['profesores_id' => 24 , 'materias_id' => 38],
            ['profesores_id' => 39 , 'materias_id' => 32],
            ['profesores_id' => 54 , 'materias_id' => 20],
            ['profesores_id' => 41 , 'materias_id' => 32],
            ['profesores_id' => 56 , 'materias_id' => 31],
            ['profesores_id' => 63 , 'materias_id' => 52],
            ['profesores_id' => 64 , 'materias_id' => 18],
            ['profesores_id' => 63 , 'materias_id' => 39],
            ['profesores_id' => 63 , 'materias_id' => 26],
            ['profesores_id' => 41 , 'materias_id' => 19],
            ['profesores_id' => 32 , 'materias_id' => 19],
            ['profesores_id' => 65 , 'materias_id' => 53],
            ['profesores_id' => 66 , 'materias_id' => 48],
            ['profesores_id' => 65 , 'materias_id' => 42],
            ['profesores_id' => 67 , 'materias_id' => 27],
            ['profesores_id' => 62 , 'materias_id' => 29],
            ['profesores_id' => 60 , 'materias_id' => 52],
            ['profesores_id' => 60 , 'materias_id' => 54],
            ['profesores_id' => 55 , 'materias_id' => 55],
            ['profesores_id' => 60 , 'materias_id' => 46],
            ['profesores_id' => 68 , 'materias_id' => 42],
            ['profesores_id' => 56 , 'materias_id' => 54],
            ['profesores_id' => 48 , 'materias_id' => 20],
            ['profesores_id' => 35 , 'materias_id' => 29],
            ['profesores_id' => 44 , 'materias_id' => 46],
            ['profesores_id' => 69 , 'materias_id' => 52],
            ['profesores_id' => 70 , 'materias_id' => 35],
            ['profesores_id' => 69 , 'materias_id' => 53],
            ['profesores_id' => 61 , 'materias_id' => 34],
            ['profesores_id' => 49 , 'materias_id' => 42],
            ['profesores_id' => 50 , 'materias_id' => 19],
            ['profesores_id' => 71 , 'materias_id' => 29],
            ['profesores_id' => 71 , 'materias_id' => 20],
            ['profesores_id' => 71 , 'materias_id' => 28],
            ['profesores_id' => 50 , 'materias_id' => 20],
            ['profesores_id' => 23 , 'materias_id' => 31],
            ['profesores_id' => 23 , 'materias_id' => 20],
            ['profesores_id' => 72 , 'materias_id' => 19],
            ['profesores_id' => 61 , 'materias_id' => 27],
            ['profesores_id' => 73 , 'materias_id' => 27],
            ['profesores_id' => 58 , 'materias_id' => 27],
            ['profesores_id' => 38 , 'materias_id' => 27],
            ['profesores_id' => 43 , 'materias_id' => 29],
            ['profesores_id' => 30 , 'materias_id' => 52],
            ['profesores_id' => 32 , 'materias_id' => 28],
            ['profesores_id' => 72 , 'materias_id' => 31],
            ['profesores_id' => 53 , 'materias_id' => 18],
            ['profesores_id' => 43 , 'materias_id' => 27],
            ['profesores_id' => 63 , 'materias_id' => 54],
            ['profesores_id' => 58 , 'materias_id' => 35],
            ['profesores_id' => 36 , 'materias_id' => 29],
            ['profesores_id' => 52 , 'materias_id' => 20],
            ['profesores_id' => 68 , 'materias_id' => 53],
            ['profesores_id' => 72 , 'materias_id' => 46],
            ['profesores_id' => 56 , 'materias_id' => 46],
            ['profesores_id' => 55 , 'materias_id' => 41],
            ['profesores_id' => 52 , 'materias_id' => 39],
            ['profesores_id' => 54 , 'materias_id' => 39],
            ['profesores_id' => 66 , 'materias_id' => 39],
            ['profesores_id' => 62 , 'materias_id' => 27],
            ['profesores_id' => 29 , 'materias_id' => 32],
            ['profesores_id' => 34 , 'materias_id' => 20],
            ['profesores_id' => 50 , 'materias_id' => 52],
            ['profesores_id' => 74 , 'materias_id' => 29],
            ['profesores_id' => 69 , 'materias_id' => 32],
            ['profesores_id' => 38 , 'materias_id' => 29],
            ['profesores_id' => 75 , 'materias_id' => 29],
            ['profesores_id' => 49 , 'materias_id' => 31],
            ['profesores_id' => 63 , 'materias_id' => 56],
            ['profesores_id' => 56 , 'materias_id' => 21],
            ['profesores_id' => 50 , 'materias_id' => 31],
            ['profesores_id' => 40 , 'materias_id' => 45],
            ['profesores_id' => 55 , 'materias_id' => 57],
            ['profesores_id' => 41 , 'materias_id' => 18],
            ['profesores_id' => 47 , 'materias_id' => 34],
            ['profesores_id' => 53 , 'materias_id' => 35],
            ['profesores_id' => 64 , 'materias_id' => 35],
            ['profesores_id' => 38 , 'materias_id' => 35],
            ['profesores_id' => 60 , 'materias_id' => 30],
            ['profesores_id' => 39 , 'materias_id' => 38],
            ['profesores_id' => 62 , 'materias_id' => 35],
            ['profesores_id' => 67 , 'materias_id' => 47],
            ['profesores_id' => 64 , 'materias_id' => 32],
            ['profesores_id' => 75 , 'materias_id' => 35],
            ['profesores_id' => 76 , 'materias_id' => 58],
            ['profesores_id' => 77 , 'materias_id' => 58],
            ['profesores_id' => 78 , 'materias_id' => 58],
            ['profesores_id' => 79 , 'materias_id' => 58],
            ['profesores_id' => 80 , 'materias_id' => 58],
            ['profesores_id' => 81 , 'materias_id' => 58],
            ['profesores_id' => 82 , 'materias_id' => 58],
            ['profesores_id' => 83 , 'materias_id' => 58],
            ['profesores_id' => 84 , 'materias_id' => 58],
            ['profesores_id' => 85 , 'materias_id' => 59],
            ['profesores_id' => 86 , 'materias_id' => 58],
            ['profesores_id' => 87 , 'materias_id' => 59],
            ['profesores_id' => 88 , 'materias_id' => 58],
            ['profesores_id' => 89 , 'materias_id' => 58],
            ['profesores_id' => 90 , 'materias_id' => 58],
            ['profesores_id' => 91 , 'materias_id' => 58],
            ['profesores_id' => 82 , 'materias_id' => 60],
            ['profesores_id' => 92 , 'materias_id' => 60],
            ['profesores_id' => 93 , 'materias_id' => 60],
            ['profesores_id' => 77 , 'materias_id' => 60],
            ['profesores_id' => 81 , 'materias_id' => 60],
            ['profesores_id' => 83 , 'materias_id' => 60],
            ['profesores_id' => 94 , 'materias_id' => 60],
            ['profesores_id' => 80 , 'materias_id' => 60],
            ['profesores_id' => 95 , 'materias_id' => 60],
            ['profesores_id' => 96 , 'materias_id' => 60],
            ['profesores_id' => 85 , 'materias_id' => 60],
            ['profesores_id' => 97 , 'materias_id' => 58],
            ['profesores_id' => 98 , 'materias_id' => 58],
            ['profesores_id' => 99 , 'materias_id' => 58],
            ['profesores_id' => 100 , 'materias_id' => 58],
            ['profesores_id' => 94 , 'materias_id' => 58],
            ['profesores_id' => 101 , 'materias_id' => 58],
            ['profesores_id' => 84 , 'materias_id' => 61],
            ['profesores_id' => 85 , 'materias_id' => 61],
            ['profesores_id' => 102 , 'materias_id' => 62],
            ['profesores_id' => 102 , 'materias_id' => 63],
            ['profesores_id' => 103 , 'materias_id' => 63],
            ['profesores_id' => 104 , 'materias_id' => 58],
            ['profesores_id' => 105 , 'materias_id' => 58],
            ['profesores_id' => 84 , 'materias_id' => 64],
            ['profesores_id' => 106 , 'materias_id' => 64],
            ['profesores_id' => 102 , 'materias_id' => 64],
            ['profesores_id' => 107 , 'materias_id' => 65],
            ['profesores_id' => 79 , 'materias_id' => 66],
            ['profesores_id' => 108 , 'materias_id' => 67],
            ['profesores_id' => 109 , 'materias_id' => 64],
            ['profesores_id' => 110 , 'materias_id' => 64],
            ['profesores_id' => 93 , 'materias_id' => 64],
            ['profesores_id' => 89 , 'materias_id' => 64],
            ['profesores_id' => 111 , 'materias_id' => 67],
            ['profesores_id' => 112 , 'materias_id' => 65],
            ['profesores_id' => 106 , 'materias_id' => 63],
            ['profesores_id' => 107 , 'materias_id' => 68],
            ['profesores_id' => 98 , 'materias_id' => 68],
            ['profesores_id' => 113 , 'materias_id' => 63],
            ['profesores_id' => 112 , 'materias_id' => 68],
            ['profesores_id' => 114 , 'materias_id' => 69],
            ['profesores_id' => 96 , 'materias_id' => 70],
            ['profesores_id' => 115 , 'materias_id' => 70],
            ['profesores_id' => 116 , 'materias_id' => 71],
            ['profesores_id' => 117 , 'materias_id' => 71],
            ['profesores_id' => 118 , 'materias_id' => 71],
            ['profesores_id' => 119 , 'materias_id' => 71],
            ['profesores_id' => 104 , 'materias_id' => 71],
            ['profesores_id' => 116 , 'materias_id' => 72],
            ['profesores_id' => 92 , 'materias_id' => 73],
            ['profesores_id' => 120 , 'materias_id' => 72],
            ['profesores_id' => 119 , 'materias_id' => 74],
            ['profesores_id' => 113 , 'materias_id' => 74],
            ['profesores_id' => 93 , 'materias_id' => 74],
            ['profesores_id' => 105 , 'materias_id' => 71],
            ['profesores_id' => 1 , 'materias_id' => 71],
            ['profesores_id' => 121 , 'materias_id' => 71],
            ['profesores_id' => 112 , 'materias_id' => 71],
            ['profesores_id' => 90 , 'materias_id' => 72],
            ['profesores_id' => 101 , 'materias_id' => 73],
            ['profesores_id' => 122 , 'materias_id' => 74],
            ['profesores_id' => 123 , 'materias_id' => 74],
            ['profesores_id' => 109 , 'materias_id' => 69],
            ['profesores_id' => 124 , 'materias_id' => 69],
            ['profesores_id' => 77 , 'materias_id' => 68],
            ['profesores_id' => 86 , 'materias_id' => 68],
            ['profesores_id' => 125 , 'materias_id' => 75],
            ['profesores_id' => 126 , 'materias_id' => 75],
            ['profesores_id' => 103 , 'materias_id' => 75],
            ['profesores_id' => 83 , 'materias_id' => 63],
            ['profesores_id' => 127 , 'materias_id' => 63],
            ['profesores_id' => 128 , 'materias_id' => 63],
            ['profesores_id' => 112 , 'materias_id' => 63],
            ['profesores_id' => 129 , 'materias_id' => 63],
            ['profesores_id' => 130 , 'materias_id' => 70],
            ['profesores_id' => 130 , 'materias_id' => 76],
            ['profesores_id' => 119 , 'materias_id' => 70],
            ['profesores_id' => 99 , 'materias_id' => 76],
            ['profesores_id' => 126 , 'materias_id' => 70],
            ['profesores_id' => 120 , 'materias_id' => 76],
            ['profesores_id' => 109 , 'materias_id' => 63],
            ['profesores_id' => 96 , 'materias_id' => 63],
            ['profesores_id' => 94 , 'materias_id' => 63],
            ['profesores_id' => 85 , 'materias_id' => 70],
            ['profesores_id' => 101 , 'materias_id' => 76],
            ['profesores_id' => 111 , 'materias_id' => 76],
            ['profesores_id' => 90 , 'materias_id' => 76],
            ['profesores_id' => 127 , 'materias_id' => 77],
            ['profesores_id' => 97 , 'materias_id' => 78],
            ['profesores_id' => 87 , 'materias_id' => 78],
            ['profesores_id' => 98 , 'materias_id' => 77],
            ['profesores_id' => 104 , 'materias_id' => 78],
            ['profesores_id' => 116 , 'materias_id' => 78],
            ['profesores_id' => 88 , 'materias_id' => 77],
            ['profesores_id' => 127 , 'materias_id' => 79],
            ['profesores_id' => 81 , 'materias_id' => 78],
            ['profesores_id' => 96 , 'materias_id' => 77],
            ['profesores_id' => 96 , 'materias_id' => 78],
            ['profesores_id' => 131 , 'materias_id' => 77],
            ['profesores_id' => 132 , 'materias_id' => 80],
            ['profesores_id' => 133 , 'materias_id' => 81],
            ['profesores_id' => 133 , 'materias_id' => 82],
            ['profesores_id' => 133 , 'materias_id' => 80],
            ['profesores_id' => 134 , 'materias_id' => 83],
            ['profesores_id' => 134 , 'materias_id' => 84],
            ['profesores_id' => 135 , 'materias_id' => 80],
            ['profesores_id' => 136 , 'materias_id' => 83],
            ['profesores_id' => 136 , 'materias_id' => 85],
            ['profesores_id' => 136 , 'materias_id' => 86],
            ['profesores_id' => 18 , 'materias_id' => 85],
            ['profesores_id' => 18 , 'materias_id' => 81],
            ['profesores_id' => 18 , 'materias_id' => 82],
            ['profesores_id' => 137 , 'materias_id' => 82],
            ['profesores_id' => 137 , 'materias_id' => 80],
            ['profesores_id' => 138 , 'materias_id' => 85],
            ['profesores_id' => 138 , 'materias_id' => 80],
            ['profesores_id' => 138 , 'materias_id' => 87],
            ['profesores_id' => 139 , 'materias_id' => 80],
            ['profesores_id' => 139 , 'materias_id' => 87],
            ['profesores_id' => 140 , 'materias_id' => 87],
            ['profesores_id' => 141 , 'materias_id' => 84],
            ['profesores_id' => 141 , 'materias_id' => 87],
            ['profesores_id' => 142 , 'materias_id' => 81],
            ['profesores_id' => 143 , 'materias_id' => 83],
            ['profesores_id' => 143 , 'materias_id' => 80],
            ['profesores_id' => 144 , 'materias_id' => 85],
            ['profesores_id' => 144 , 'materias_id' => 80],
            ['profesores_id' => 145 , 'materias_id' => 82],
            ['profesores_id' => 145 , 'materias_id' => 80],
            ['profesores_id' => 145 , 'materias_id' => 87],
            ['profesores_id' => 146 , 'materias_id' => 82],
            ['profesores_id' => 146 , 'materias_id' => 85],
            ['profesores_id' => 147 , 'materias_id' => 80],
            ['profesores_id' => 147 , 'materias_id' => 83],
            ['profesores_id' => 147 , 'materias_id' => 87],
            ['profesores_id' => 148 , 'materias_id' => 83],
            ['profesores_id' => 148 , 'materias_id' => 80],
            ['profesores_id' => 149 , 'materias_id' => 83],
            ['profesores_id' => 149 , 'materias_id' => 80],
            ['profesores_id' => 150 , 'materias_id' => 85],
            ['profesores_id' => 150 , 'materias_id' => 80],
            ['profesores_id' => 150 , 'materias_id' => 87],
            ['profesores_id' => 150 , 'materias_id' => 86],
            ['profesores_id' => 151 , 'materias_id' => 82],
            ['profesores_id' => 151 , 'materias_id' => 84],
            ['profesores_id' => 151 , 'materias_id' => 87],
            ['profesores_id' => 152 , 'materias_id' => 88],
            ['profesores_id' => 152 , 'materias_id' => 89],
            ['profesores_id' => 152 , 'materias_id' => 90],
            ['profesores_id' => 152 , 'materias_id' => 91],
            ['profesores_id' => 152 , 'materias_id' => 75],
            ['profesores_id' => 153 , 'materias_id' => 92],
            ['profesores_id' => 153 , 'materias_id' => 93],
            ['profesores_id' => 153 , 'materias_id' => 88],
            ['profesores_id' => 154 , 'materias_id' => 89],
            ['profesores_id' => 154 , 'materias_id' => 93],
            ['profesores_id' => 154 , 'materias_id' => 88],
            ['profesores_id' => 155 , 'materias_id' => 94],
            ['profesores_id' => 156 , 'materias_id' => 95],
            ['profesores_id' => 156 , 'materias_id' => 92],
            ['profesores_id' => 156 , 'materias_id' => 88],
            ['profesores_id' => 156 , 'materias_id' => 75],
            ['profesores_id' => 157 , 'materias_id' => 95],
            ['profesores_id' => 157 , 'materias_id' => 89],
            ['profesores_id' => 157 , 'materias_id' => 88],
            ['profesores_id' => 158 , 'materias_id' => 89],
            ['profesores_id' => 158 , 'materias_id' => 88],
            ['profesores_id' => 159 , 'materias_id' => 89],
            ['profesores_id' => 159 , 'materias_id' => 93],
            ['profesores_id' => 159 , 'materias_id' => 94],
            ['profesores_id' => 160 , 'materias_id' => 89],
            ['profesores_id' => 161 , 'materias_id' => 94],
            ['profesores_id' => 137 , 'materias_id' => 96],
            ['profesores_id' => 138 , 'materias_id' => 97],
            ['profesores_id' => 162 , 'materias_id' => 85],
            ['profesores_id' => 140 , 'materias_id' => 97],
            ['profesores_id' => 140 , 'materias_id' => 96],
            ['profesores_id' => 141 , 'materias_id' => 98],
            ['profesores_id' => 141 , 'materias_id' => 97],
            ['profesores_id' => 141 , 'materias_id' => 96],
            ['profesores_id' => 142 , 'materias_id' => 97],
            ['profesores_id' => 142 , 'materias_id' => 96],
            ['profesores_id' => 144 , 'materias_id' => 98],
            ['profesores_id' => 144 , 'materias_id' => 97],
            ['profesores_id' => 163 , 'materias_id' => 98],
            ['profesores_id' => 163 , 'materias_id' => 97],
            ['profesores_id' => 163 , 'materias_id' => 96],
            ['profesores_id' => 149 , 'materias_id' => 98],
            ['profesores_id' => 149 , 'materias_id' => 96],
            ['profesores_id' => 164 , 'materias_id' => 98],
            ['profesores_id' => 164 , 'materias_id' => 97],
            ['profesores_id' => 165 , 'materias_id' => 99],
            ['profesores_id' => 165 , 'materias_id' => 100],
            ['profesores_id' => 166 , 'materias_id' => 101],
            ['profesores_id' => 166 , 'materias_id' => 99],
            ['profesores_id' => 166 , 'materias_id' => 100],
            ['profesores_id' => 167 , 'materias_id' => 101],
            ['profesores_id' => 167 , 'materias_id' => 102],
            ['profesores_id' => 167 , 'materias_id' => 100],
            ['profesores_id' => 168 , 'materias_id' => 103],
            ['profesores_id' => 168 , 'materias_id' => 101],
            ['profesores_id' => 168 , 'materias_id' => 104],
            ['profesores_id' => 169 , 'materias_id' => 101],
            ['profesores_id' => 169 , 'materias_id' => 100],
            ['profesores_id' => 170 , 'materias_id' => 101],
            ['profesores_id' => 171 , 'materias_id' => 103],
            ['profesores_id' => 172 , 'materias_id' => 103],
            ['profesores_id' => 172 , 'materias_id' => 101],
            ['profesores_id' => 172 , 'materias_id' => 102],
            ['profesores_id' => 172 , 'materias_id' => 104],
            ['profesores_id' => 172 , 'materias_id' => 100],
            ['profesores_id' => 173 , 'materias_id' => 103],
            ['profesores_id' => 173 , 'materias_id' => 102],
            ['profesores_id' => 173 , 'materias_id' => 104],
            ['profesores_id' => 173 , 'materias_id' => 100],
            ['profesores_id' => 174 , 'materias_id' => 101],
            ['profesores_id' => 174 , 'materias_id' => 100],
            ['profesores_id' => 175 , 'materias_id' => 103],
            ['profesores_id' => 175 , 'materias_id' => 101],
            ['profesores_id' => 176 , 'materias_id' => 103],
            ['profesores_id' => 176 , 'materias_id' => 104],
            ['profesores_id' => 176 , 'materias_id' => 100],
            ['profesores_id' => 177 , 'materias_id' => 103],
            ['profesores_id' => 177 , 'materias_id' => 102],
            ['profesores_id' => 177 , 'materias_id' => 104],
            ['profesores_id' => 178 , 'materias_id' => 103],
            ['profesores_id' => 178 , 'materias_id' => 101],
            ['profesores_id' => 178 , 'materias_id' => 102],
            ['profesores_id' => 178 , 'materias_id' => 104],
            ['profesores_id' => 179 , 'materias_id' => 105],
            ['profesores_id' => 179 , 'materias_id' => 106],
            ['profesores_id' => 180 , 'materias_id' => 107],
            ['profesores_id' => 180 , 'materias_id' => 108],
            ['profesores_id' => 180 , 'materias_id' => 109],
            ['profesores_id' => 180 , 'materias_id' => 105],
            ['profesores_id' => 180 , 'materias_id' => 110],
            ['profesores_id' => 181 , 'materias_id' => 111],
            ['profesores_id' => 182 , 'materias_id' => 109],
            ['profesores_id' => 182 , 'materias_id' => 105],
            ['profesores_id' => 182 , 'materias_id' => 112],
            ['profesores_id' => 182 , 'materias_id' => 110],
            ['profesores_id' => 182 , 'materias_id' => 113],
            ['profesores_id' => 182 , 'materias_id' => 114],
            ['profesores_id' => 183 , 'materias_id' => 111],
            ['profesores_id' => 183 , 'materias_id' => 115],
            ['profesores_id' => 183 , 'materias_id' => 116],
            ['profesores_id' => 183 , 'materias_id' => 113],
            ['profesores_id' => 184 , 'materias_id' => 115],
            ['profesores_id' => 184 , 'materias_id' => 105],
            ['profesores_id' => 184 , 'materias_id' => 106],
            ['profesores_id' => 184 , 'materias_id' => 117],
            ['profesores_id' => 185 , 'materias_id' => 108],
            ['profesores_id' => 185 , 'materias_id' => 112],
            ['profesores_id' => 185 , 'materias_id' => 109],
            ['profesores_id' => 185 , 'materias_id' => 113],
            ['profesores_id' => 186 , 'materias_id' => 113],
            ['profesores_id' => 186 , 'materias_id' => 116],
            ['profesores_id' => 186 , 'materias_id' => 105],
            ['profesores_id' => 187 , 'materias_id' => 107],
            ['profesores_id' => 187 , 'materias_id' => 115],
            ['profesores_id' => 187 , 'materias_id' => 113],
            ['profesores_id' => 188 , 'materias_id' => 105],
            ['profesores_id' => 188 , 'materias_id' => 106],
            ['profesores_id' => 189 , 'materias_id' => 112],
            ['profesores_id' => 189 , 'materias_id' => 113],
            ['profesores_id' => 189 , 'materias_id' => 106],
            ['profesores_id' => 190 , 'materias_id' => 115],
            ['profesores_id' => 190 , 'materias_id' => 113],
            ['profesores_id' => 190 , 'materias_id' => 106],
            ['profesores_id' => 191 , 'materias_id' => 105],
            ['profesores_id' => 191 , 'materias_id' => 118],
            ['profesores_id' => 191 , 'materias_id' => 106],
            ['profesores_id' => 192 , 'materias_id' => 112],
            ['profesores_id' => 192 , 'materias_id' => 113],
            ['profesores_id' => 193 , 'materias_id' => 113],
            ['profesores_id' => 193 , 'materias_id' => 118],
            ['profesores_id' => 194 , 'materias_id' => 115],
            ['profesores_id' => 195 , 'materias_id' => 113],
            ['profesores_id' => 196 , 'materias_id' => 105],
            ['profesores_id' => 196 , 'materias_id' => 115],
            ['profesores_id' => 197 , 'materias_id' => 108],
            ['profesores_id' => 197 , 'materias_id' => 105],
            ['profesores_id' => 197 , 'materias_id' => 113],
            ['profesores_id' => 198 , 'materias_id' => 116],
            ['profesores_id' => 198 , 'materias_id' => 105],
            ['profesores_id' => 198 , 'materias_id' => 113],
            ['profesores_id' => 199 , 'materias_id' => 107],
            ['profesores_id' => 199 , 'materias_id' => 108],
            ['profesores_id' => 199 , 'materias_id' => 105],
            ['profesores_id' => 199 , 'materias_id' => 113],
        ];

        //Catalogos
        foreach($materias as $materia){
            Materia::create($materia);
        }

        foreach($c_quejas as $c_queja){
            CQueja::create($c_queja);
        }
        
        foreach($academias as $academia){
            Academia::create($academia);
        };

        //Random Values
        User::factory(200)->create();

        foreach($profesores as $profesor){
            Profesor::create($profesor);
        };

        foreach($profesores_materias as $profesor_materia){
            ProfesorMateria::create($profesor_materia);
        };
    }
}
